server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: db-service
          uri: http://localhost:8081/
          predicates:
              - Path=/api/db-service/**
        - id: auth-service
          uri: http://localhost:8082/
          predicates:
            - Path=/api/auth-service/**

